version: '3.8'

services:
  bumbo:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app:app --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/app
    ports:
      - '8000:8000'